language: python
python:
- '3.6'
deploy:
  provider: pypi
  on:
    tags: true
  user: tcprescott
  password:
    secure: mM2SqK2OuPZGvK5SqRoty8DIGeJ3oZd4mjS7xHVlYmIxQZmsqFQCtHi5bXaClOewb2jvUiRvLaL6skI9yke7Btk10ZFyyIOr3NLKtsYLJiOYZlANkH+LTHvan6zbDq1OhYSDKFD1PCTKrPhEglLKie9Co6ErVFBUl3wFEMGFksK/aMBRUkOyi+om14PxSNpyIwiO6KiIxa+l7leRyZvmpM796G01iKh2XEAuLXVWOpbinSTubzXfqD8iLiHgHsw7/KKEbuZ5pvM8SmvieqBEbRxuWj1awih/iaMr4e1gP5hHb5Nri91Nf+P3oag4K7SO6zo/1n0S5uRjr6HEwGsbLxMDtedzEe3cUFmv9K5aglhoDslZXHmdkjvdcNToShbHbv7dzuWD7rBIvE2+yQ1ku315ZR1x6shAqt4TGHSbypIYJfi3Qv8UK40RHIZckK0qISFba4356FPAc2yj66QtLy5+SXI28KzJx90h4E+9w/jrS8q8XzP8DTTfrWhtuqtNzyolGUwEeG3hPDkp/tSCZzPTWcLwu8sBLCHvicAl3B07yQXtYvWox9wYx+3rbFynGJhCa6P0PbBXnv4LtZIf7dh+rGlCFNEslPIzLgozJyoFizRVzuZuON0A9GtVIQjnKXyoMTNZBnNMwc26A/txDnp84b9fvacxfGb7J+rACnM=
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
