language: python
python:
- '3.6'
deploy:
  provider: pypi
  on:
    tags: true
  user: tcprescott
  password:
    secure: ne1AdPw7wiEvvdV1FB0rKBoOG5cPTVFcUfAUM2pVVwNeQksCe7FZpXdS9UToSeatC6ypidjMiTcgTM4LyBa0JfoV9mZv8/UJiJp0/8WfLO6/NrdOByQu/AVlbsh2Z3MRKh7WnqxnL8T3QtMeojIag4+0dPO0bL96hn1dn7R6szpKrKxL6j7khYS4Gau8mU7jaH9UYxweZrE9Hi+2XK+VUhlrhwJJhb/ScTZEg2XprGvIpN+3hsChUhYwmXtN4h5XQq6mUH76da9+x+GuIKPGG0TjAYgEI/bOwopGRSFSStE2fOPMY/hp8SLR2DOL7lZNbfRM9+B+uXEUcprYoVnUqQAA6JXnu3ts2RzzQONHRAvjUVSdSQ5kY/SxZGYDs7ioTk18pgGWMhwwEB+yL4EDPBAE3AnSh2JbyVIFWpblQlZlfPY8fZg1VpRQTixZZdWot8pltWsDb1kAxK1qS4zAygmywiXHhQv+k2793QckJ+i0YcA0jtUnY2u+9Ez9Ql2VJxnKP9E3WusowSswUDAeemRXv6fggKiw+xrSjfRiV+Qbhs8gFusinFmBxCzhQSKlVoGLH4ij4riEi9hQhlQHMUUwfZPwk8KEIUPSjTL1E2YTsVgfWKbV+np6KK17mdTLs6bU9jyf/uzeA1m6oK+OgUQClQHOVJn5GwvniJKhJ/w=
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
